### ISSUE TITLE
前端项目打包启动报错

### ISSUE THREAD

**Issue by shenhequnying** [Aliceco/react-umi-admin#1]
![image](https://user-images.githubusercontent.com/6714111/84139836-2ff14480-aa83-11ea-8f2f-c5f1e007c3ce.png)

**Comment by Ans1998** [comment]
我这边执行 打包命令是可以的。 这个是使用umi框架进行开发的，你环境需要装一下umi环境（https://umijs.org/zh-CN）然后在执行yran  build

**Comment by shenhequnying** [comment]
> 我这边执行 打包命令是可以的。 这个是使用umi框架进行开发的，你环境需要装一下umi环境（[https://umijs.org/zh-CN）然后在执行yran](https://umijs.org/zh-CN%EF%BC%89%E7%84%B6%E5%90%8E%E5%9C%A8%E6%89%A7%E8%A1%8Cyran) build

奇怪，正常yarn 不是应该已经添加依赖了。。

**Comment by Ans1998** [comment]
你去看看umi官网

**Comment by shenhequnying** [comment]
> 我这边执行 打包命令是可以的。 这个是使用umi框架进行开发的，你环境需要装一下umi环境（[https://umijs.org/zh-CN）然后在执行yran](https://umijs.org/zh-CN%EF%BC%89%E7%84%B6%E5%90%8E%E5%9C%A8%E6%89%A7%E8%A1%8Cyran) build

我这边是
os: win10
node: 12.16.3
